services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sharyo

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
